### ISSUE TITLE
Please change the font to something not Comic Sans

### ISSUE THREAD

**Issue by FatOrangutan** [NanoAdblocker/NanoIcon#1]
Unsure if you are open to this idea, but it looks a lot more professional without that font...

Quick SVG:
![nano](https://user-images.githubusercontent.com/8336638/34401832-c095cb90-ebc3-11e7-9c2a-c802bcff0df5.png)

**Comment by jspenguin2017** [comment]
Nah, I like my icon. I want it to be quite different than uBO's icon. 
Nano isn't meant to be super "professional", it is a fun personal project.
